"""Generate idna_tables.go: the IDNA 2008 data the Python reference validates labels with.

The reference encodes hosts with the ``idna`` package (its codepoint classes, joining types and
scripts) plus CPython's ``unicodedata`` (bidi classes, combining classes), and detects IDNA
2003/2008 ambiguity with the stdlib ``idna`` codec (Unicode 3.2 stringprep). Run from python/:

    uv run python ../go/internal/safety/idna_tables_gen.py | gofmt > ../go/internal/safety/idna_tables.go
"""

import stringprep
import sys
import unicodedata

import idna
from idna import idnadata

CPS = [c for c in range(0x110000) if not 0xD800 <= c < 0xE000]


def intranges(ranges):
    return [(r >> 32, (r & 0xFFFFFFFF) - 1) for r in ranges]


def ranges(pred):
    out, start, prev = [], None, None
    for c in CPS:
        if pred(c):
            if start is None:
                start = c
            elif c != prev + 1:
                out.append((start, prev))
                start = c
            prev = c
        # surrogate gap breaks ranges naturally
    if start is not None:
        out.append((start, prev))
    return out


def emit(name, rs, doc):
    print(f"// {doc}")
    print(f"var {name} = []idnaRange{{")
    for lo, hi in rs:
        print(f"\t{{0x{lo:04X}, 0x{hi:04X}}},")
    print("}")
    print()


print(f"// Code generated by idna_tables_gen.py from idna {idna.__version__} (IDNA data "
      f"{idnadata.__version__}) and CPython unicodedata {unicodedata.unidata_version}; DO NOT EDIT.")
print()
print("package safety")
print()
emit("idnaPVALID", intranges(idnadata.codepoint_classes["PVALID"]), "IDNA 2008 PVALID code points.")
emit("idnaCONTEXTJ", intranges(idnadata.codepoint_classes["CONTEXTJ"]), "IDNA 2008 CONTEXTJ code points.")
emit("idnaCONTEXTO", intranges(idnadata.codepoint_classes["CONTEXTO"]), "IDNA 2008 CONTEXTO code points.")
for jt in ("L", "D", "R", "T"):
    emit(f"joiningType{jt}", intranges(idnadata.joining_types[jt]), f"Joining type {jt}.")
for script in ("Greek", "Hebrew", "Hiragana", "Katakana", "Han"):
    emit(f"script{script}", intranges(idnadata.scripts[script]), f"Script {script}.")
emit("viramaCombining", ranges(lambda c: unicodedata.combining(chr(c)) == 9),
     "Canonical combining class 9 (virama), CPython unicodedata.")
emit("unicodeDataUnnamed", ranges(lambda c: unicodedata.combining(chr(c)) == 0 and not unicodedata.name(chr(c), "")),
     "Code points with combining class 0 and no unicodedata name (idna's _combining_class raises).")
emit("unicodeMark", ranges(lambda c: unicodedata.category(chr(c))[0] == "M"),
     "General category M*, CPython unicodedata.")
emit("assignedUnicode32", ranges(lambda c: unicodedata.ucd_3_2_0.category(chr(c)) != "Cn"),
     "Code points assigned in Unicode 3.2 (the stdlib idna codec's nameprep tables).")
# bidi classes as (lo, hi, class) triples
classes = sorted({unicodedata.bidirectional(chr(c)) for c in CPS})
print("// Bidi classes (CPython unicodedata.bidirectional); \"\" means unassigned.")
print("const (")
for i, cls in enumerate(classes):
    name = cls or "None"
    print(f"\tbidi{name} bidiClass = {i}")
print(")")
print()
print("var bidiClassNames = [...]string{" + ", ".join(f'"{c}"' for c in classes) + "}")
print()
print("var bidiTable = []bidiRange{")
start, prev, cur = None, None, None
for c in CPS:
    cls = unicodedata.bidirectional(chr(c))
    if start is None:
        start, prev, cur = c, c, cls
        continue
    if cls != cur or c != prev + 1:
        print(f"\t{{0x{start:04X}, 0x{prev:04X}, bidi{cur or 'None'}}},")
        start, cur = c, cls
    prev = c
print(f"\t{{0x{start:04X}, 0x{prev:04X}, bidi{cur or 'None'}}},")
print("}")


def stringprep_ranges(pred):
    return ranges(lambda c: pred(chr(c)))


emit("stringprepProhibited", stringprep_ranges(lambda ch: any(
    f(ch) for f in (stringprep.in_table_c12, stringprep.in_table_c22, stringprep.in_table_c3,
                    stringprep.in_table_c4, stringprep.in_table_c5, stringprep.in_table_c6,
                    stringprep.in_table_c7, stringprep.in_table_c8, stringprep.in_table_c9))),
     "RFC 3454 tables C.1.2, C.2.2 and C.3-C.9 (nameprep prohibited output).")
emit("stringprepRandAL", stringprep_ranges(stringprep.in_table_d1), "RFC 3454 table D.1 (RandALCat).")
emit("stringprepL", stringprep_ranges(stringprep.in_table_d2), "RFC 3454 table D.2 (LCat).")
