//go:build ignore

// idna_overrides_gen.go writes idna_overrides.go: the code points whose per-character host
// mapping in the Python reference differs from x/net/idna's (see idna_overrides_dump.py).
package main

import (
	"encoding/json"
	"fmt"
	"os"
	"sort"
	"strconv"
	"strings"

	"golang.org/x/net/idna"
)

var (
	uts46Map = idna.New(idna.MapForLookup(), idna.Transitional(false), idna.StrictDomainName(false),
		idna.CheckHyphens(false), idna.CheckJoiners(false))
	uts46TransitionalMap = idna.New(idna.MapForLookup(), idna.Transitional(true),
		idna.StrictDomainName(false), idna.CheckHyphens(false), idna.CheckJoiners(false))
)

// These two functions must stay identical to mapRune2008 / mapRune2003 in idna.go (minus the
// override lookup).
func goModern(r rune) (string, bool) {
	out, err := uts46Map.ToUnicode("0" + string(r))
	if err != nil || !strings.HasPrefix(out, "0") {
		return "", false
	}
	return out[1:], true
}

// goLegacy falls back to the character itself where the transitional mapping disallows it
// (nameprep leaves such characters alone; its prohibited-output tables reject them later).
func goLegacy(r rune) string {
	ascii, err := uts46TransitionalMap.ToASCII("0" + string(r))
	if err != nil {
		return string(r)
	}
	out, err := idna.Punycode.ToUnicode(ascii)
	if err != nil || !strings.HasPrefix(out, "0") {
		return string(r)
	}
	return out[1:]
}

type dump struct {
	Modern     map[string]*string `json:"modern"`
	Doomed     []rune             `json:"doomed"`
	Legacy     map[string]string  `json:"legacy"`
	Assigned32 []rune             `json:"assigned32"`
	IDNA       string             `json:"idna"`
}

func main() {
	raw, err := os.ReadFile(os.Args[1])
	if err != nil {
		panic(err)
	}
	var d dump
	if err := json.Unmarshal(raw, &d); err != nil {
		panic(err)
	}
	doomed := map[rune]bool{}
	for _, c := range d.Doomed {
		doomed[c] = true
	}
	type entry struct {
		r   rune
		out string
		ok  bool
	}
	var modern, legacy []entry
	for c := rune(0); c < 0x110000; c++ {
		if c >= 0xD800 && c < 0xE000 {
			continue
		}
		pyOut, pyOK := string(c), true
		if v, ok := d.Modern[strconv.Itoa(int(c))]; ok {
			if v == nil {
				pyOK = false
			} else {
				pyOut = *v
			}
		}
		if doomed[c] {
			pyOK = false
		}
		goOut, goOK := goModern(c)
		if pyOK != goOK || (pyOK && pyOut != goOut) {
			modern = append(modern, entry{c, pyOut, pyOK})
		}
	}
	for _, c := range d.Assigned32 {
		pyOut := string(c)
		if v, ok := d.Legacy[strconv.Itoa(int(c))]; ok {
			pyOut = v
		}
		if goLegacy(c) != pyOut {
			legacy = append(legacy, entry{c, pyOut, true})
		}
	}
	sort.Slice(modern, func(i, j int) bool { return modern[i].r < modern[j].r })
	fmt.Printf("// Code generated by idna_overrides_gen.go from idna %s; DO NOT EDIT.\n\n", d.IDNA)
	fmt.Println("package safety")
	fmt.Println()
	fmt.Println("// idna2008Overrides: per-code-point UTS #46 mappings (non-transitional, STD3 off) where the")
	fmt.Println("// reference's idna tables differ from x/net/idna's; ok=false means disallowed.")
	fmt.Println("var idna2008Overrides = map[rune]runeMapping{")
	for _, e := range modern {
		fmt.Printf("\t0x%04X: {%s, %v},\n", e.r, strconv.QuoteToASCII(e.out), e.ok)
	}
	fmt.Println("}")
	fmt.Println()
	fmt.Println("// idna2003Overrides: per-code-point nameprep mappings (B.1 / B.2 / NFKC over Unicode 3.2)")
	fmt.Println("// where the transitional UTS #46 mapping of x/net/idna differs.")
	fmt.Println("var idna2003Overrides = map[rune]string{")
	for _, e := range legacy {
		fmt.Printf("\t0x%04X: %s,\n", e.r, strconv.QuoteToASCII(e.out))
	}
	fmt.Println("}")
}
