/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Which implementation serves, and whether its dependencies are reachable */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/missions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Missions, most recently updated first */
        get: operations["listMissions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/missions/{mission_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One mission: its row, spend, items, and live workflow state when durable */
        get: operations["getMission"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/missions/{mission_id}/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The mission's checklist, from its anchor */
        get: operations["listItems"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/missions/{mission_id}/items/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * One checklist item: its dependents, its cycles, their spend and the events about it
         * @description An event is about the item when its payload's `item_id` or `item` is the item's id, its `items` holds the id, or it was recorded in one of the item's cycles. The item's cycles are the (non-empty) `cycle_id`s of the events whose `item_id` or `item` is the item's id, in the order first recorded; `spend` sums the cost ledger's calls in those cycles.
         */
        get: operations["getItem"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/missions/{mission_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The mission's recorded events after a cursor, oldest first */
        get: operations["listEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/missions/{mission_id}/costs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The mission's cost ledger: totals, totals by role and by model, and the most recent calls */
        get: operations["listCosts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/missions/{mission_id}/gates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The mission's human gates, most recently opened first */
        get: operations["listGates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Live events as Server-Sent Events
         * @description A Server-Sent Events stream. Each `mission_event` message carries one `MissionEvent` as `data`, with its id as the SSE `id`, so a reconnecting `EventSource` resumes after the last one it saw (`Last-Event-ID`). A `mission` message carries a `MissionSummary` when a mission's row changes (it has no id). A comment line is sent every 15 seconds so idle connections stay open. Every client is served by one shared reader; the stream never polls per client.
         */
        get: operations["streamEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/missions/{mission_id}/steer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add a steering note to every following cycle's prompt (`steer_v1`)
         * @description Sends the `steer_v1` signal, as `lha mission-steer` does. The note is trimmed; a note that is empty after trimming is refused (422).
         */
        post: operations["steerMission"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/missions/{mission_id}/snooze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sleep before the next cycle, or wake (`snooze_v1`)
         * @description Sends the `snooze_v1` signal, as `lha mission-snooze` does: the mission sleeps `seconds` before its next cycle; 0 wakes it.
         */
        post: operations["snoozeMission"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/missions/{mission_id}/checklist-edits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Edit the checklist as one atomic batch (`checklist_edit_v1`)
         * @description Sends the `checklist_edit_v1` signal, as `lha mission-edit` does. The workflow validates the batch against the checklist before its next cycle; one bad edit refuses the whole batch.
         */
        post: operations["editChecklist"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/missions/{mission_id}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Answer the open human gate, recording who answered (`human_decision_v2`)
         * @description Sends the `human_decision_v2` signal, as `lha mission-approve --as` does. The decision must be one of the open gate's options (422 otherwise); with no gate open, any decision is held for the next gate. `by` is recorded on the gate row. Not available over MCP: an agent must not answer its own gates.
         */
        post: operations["decideGate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/missions/{mission_id}/abort": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Abort the mission (a workflow cancellation)
         * @description Cancels the mission's workflow, as `lha mission-abort` does. Not available over MCP.
         */
        post: operations["abortMission"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            error: {
                /** @enum {string} */
                code: "unauthorized" | "forbidden_host" | "not_found" | "anchor_unavailable" | "not_durable" | "finished" | "invalid_request" | "temporal_unavailable";
                message: string;
            };
        };
        Accepted: {
            /** @constant */
            accepted: true;
        };
        Health: {
            /** @description This document's `info.version`. */
            api_version: string;
            /** @description `python`, `go` or `rust`: which implementation serves. Informational only. */
            implementation: string;
            lha_version: string;
            store: {
                /** @enum {string} */
                backend: "sqlite" | "postgres";
                /** @description Non-empty when a configured Postgres is unusable and SQLite is read instead. */
                degraded_reason: string;
            };
            /** @enum {string} */
            temporal: "connected" | "unavailable" | "not_configured";
        };
        /** @description Spend recorded in the cost ledger. `known_usd` sums the calls with a known cost; a call whose cost is unknown is counted, never valued at $0. */
        CostSummary: {
            calls: number;
            known_usd: number;
            unknown_cost_calls: number;
            input_tokens: number;
            output_tokens: number;
        };
        ItemCounts: {
            total: number;
            todo: number;
            in_progress: number;
            blocked: number;
            done: number;
            split: number;
        };
        MissionSummary: {
            mission_id: string;
            title: string;
            /** @description The store's status: `RUNNING`, `SLEEPING`, `WAITING_ON_HUMAN`, `DEGRADED_PARK`, `DONE`, `ABORTED`, `IMPOSSIBLE`, or a local run's status. A client shows an unknown status as it is. */
            status: string;
            /** @description Run by a Temporal workflow (controls are available). */
            durable: boolean;
            workflow_id: string | null;
            head_sha: string | null;
            created_at: string;
            updated_at: string;
            spend: components["schemas"]["CostSummary"];
            /** @description `null` when the anchor cannot be read here. */
            items: components["schemas"]["ItemCounts"] | null;
            last_event: {
                id: number;
                ts: string;
                kind: string;
            } | null;
        };
        /** @description A `MissionSummary` plus the mission's description, workdir and live workflow state. */
        MissionDetail: {
            mission_id: string;
            title: string;
            /** @description The store's status: `RUNNING`, `SLEEPING`, `WAITING_ON_HUMAN`, `DEGRADED_PARK`, `DONE`, `ABORTED`, `IMPOSSIBLE`, or a local run's status. A client shows an unknown status as it is. */
            status: string;
            /** @description Run by a Temporal workflow (controls are available). */
            durable: boolean;
            workflow_id: string | null;
            head_sha: string | null;
            created_at: string;
            updated_at: string;
            spend: components["schemas"]["CostSummary"];
            /** @description `null` when the anchor cannot be read here. */
            items: components["schemas"]["ItemCounts"] | null;
            last_event: {
                id: number;
                ts: string;
                kind: string;
            } | null;
            description: string;
            /** @description Where the mission's anchor is, as recorded by its run. */
            workdir: string | null;
            /** @description The workflow's own state; `null` for a local run, a finished mission, or when Temporal is unreachable (see `live_error`). */
            live: components["schemas"]["LiveState"] | null;
            live_error: string | null;
        };
        /** @description The answers to the workflow's queries (the wire contract), fetched at most every few seconds per mission and shared. */
        LiveState: {
            status: string;
            cycles: number;
            gate: components["schemas"]["OpenGate"] | null;
            open_question: string | null;
            /** @description When a sleeping mission wakes (ISO-8601 UTC). */
            resume_at: string | null;
            steer_notes: string[];
            pending_edits: number;
        };
        OpenGate: {
            gate_id: string;
            /** @enum {string} */
            kind: "tool_call" | "deadlock";
            question: string;
            options: string[];
            default_action: string;
            opened_at: string;
            deadline: string;
            escalations_sent: number;
            next_escalation_at: string;
            recommended: string;
            /** @description The irreversible action awaiting approval (a `tool_call` gate). */
            request: {
                tool: string;
                arguments: string;
                reason: string;
                fingerprint: string;
            } | null;
        };
        ChecklistItem: {
            id: string;
            description: string;
            /** @enum {string} */
            status: "todo" | "in_progress" | "blocked" | "done" | "split";
            verified_by: string[];
            depends_on: string[];
            attempts: number;
            consecutive_failures: number;
            last_failure: string;
            allow_harness_edits: boolean;
            witnesses: string[];
            notes: string;
            schema_version: number;
        };
        /** @description One edit of a `checklist_edit_v1` batch (`spec/state/checklist_edit.json`): `add` takes a description; every other op takes the `id` of the item it changes. */
        ChecklistEdit: {
            /** @enum {string} */
            op: "add" | "remove" | "edit" | "reopen" | "block" | "unblock";
            id?: string;
            description?: string;
            witnesses?: string[];
            depends_on?: string[];
            after?: string;
            allow_harness_edits?: boolean;
            notes?: string;
        };
        /** @description One row of `mission_events`. For every kind in `spec/obs/mission_events.json`, `payload` matches that kind's schema. */
        MissionEvent: {
            id: number;
            mission_id: string;
            cycle_id: string;
            /** @description When it was recorded (ISO-8601 UTC). */
            ts: string;
            /** @description The event kind. A client ignores kinds it does not know. */
            kind: string;
            payload: {
                [key: string]: unknown;
            };
            schema_version: number;
        } & (unknown & unknown & unknown & unknown & unknown & unknown & unknown & unknown & unknown & unknown & unknown & unknown & unknown & unknown & unknown & unknown & unknown & unknown & unknown & unknown & unknown & unknown & unknown & unknown & unknown & unknown & unknown & unknown & unknown & unknown & unknown & unknown & unknown & unknown & unknown & unknown & unknown);
        CostCall: {
            cycle_id: string;
            role: string;
            model: string;
            input_tokens: number;
            output_tokens: number;
            /** @description `null` when the call's cost is unknown (never $0). */
            usd: number | null;
            ts: string;
        };
        Gate: {
            gate_id: string;
            kind: string;
            /** @description `OPEN`, `ESCALATED` (a reminder was sent), `RESOLVED` or `DEFAULTED` (its deadline passed). */
            status: string;
            question: string;
            options: string[];
            default_action: string;
            risk: string;
            deadline: string;
            decision: string | null;
            /** @description Who answered (`human_decision_v2`), when known. */
            resolved_by: string | null;
            reminders: number;
            request: {
                [key: string]: string;
            } | null;
            opened_at: string;
            /** @description When it was resolved or defaulted (`""` while open). */
            resolved_at: string;
        };
        /** @description The spend of the calls sharing a role or a model, summed like `CostSummary`. */
        CostGroup: {
            /** @description The role or model. */
            key: string;
            calls: number;
            known_usd: number;
            unknown_cost_calls: number;
            input_tokens: number;
            output_tokens: number;
        };
        check_quarantined: {
            check: string;
            revision: string;
            passes: number;
            fails: number;
        };
        checkpoint: {
            head_sha: string;
            verified: boolean;
            /** @enum {string} */
            verdict: "passed" | "failed" | "unverified";
            peak_rss_mb: number;
        };
        claude_code_session: {
            turns: number;
            tool_calls: number;
            session_id: string;
            stopped: string;
        };
        code_map: {
            item_id: string;
            ok: boolean;
            /** @enum {string} */
            mode: "trace" | "task";
            duration_s: number;
            exit_code?: number;
            timed_out?: boolean;
            bytes?: number;
            error?: string;
            fell_back?: boolean;
        };
        cycle_started: {
            item_id: string;
        };
        deadlocked: {
            reason: string;
        };
        decision_chain_invalid: {
            reason: string;
        };
        governor_block: {
            reason: string;
        };
        integration: {
            item: string;
            merged: boolean;
            branch: string;
            reason: string;
        };
        invalid_reply: {
            reason: string;
        };
        lease: {
            writer: string;
            path: string;
            granted: boolean;
            why: string;
        };
        llm_turn: {
            model: string;
            output_tokens: number;
            stop_reason: string;
        };
        loop_detected: {
            item_id: string;
        };
        memory_consolidated: {
            episodes: number;
            facts: number;
            /** @enum {string} */
            mode: "model" | "extractive";
        };
        memory_degraded: {
            reason: string;
        };
        memory_error: {
            where: string;
            error: string;
        };
        memory_reembedded: {
            count: number;
            embedding_model: string;
            embedding_version: string;
        };
        model_unavailable: {
            reason: string;
        };
        ownership_released: {
            paths: string[];
        };
        ownership_violation: {
            writer: string;
            paths: string[];
        };
        opencode_session: {
            turns: number;
            tool_calls: number;
            session_id: string;
            stopped: string;
        };
        parallel_wave: {
            items: string[];
            base: string;
        };
        quarantined_check_failed: {
            check: string;
            revision: string;
            passes: number;
            fails: number;
        };
        reflection: {
            item: string;
        };
        research: {
            item: string;
            n: number;
            failed: number;
        };
        research_failed: {
            item: string;
            error: string;
        };
        resumed: {
            run: number;
            cycle_offset: number;
            board: number;
        };
        review: {
            item: string;
            blocking: boolean;
            /** @enum {string} */
            verdict: "approve" | "block" | "unparsed";
        };
        review_reopened: {
            item: string;
        };
        review_screen: {
            item: string;
            findings: number;
            forced: boolean;
        };
        sandbox_egress: {
            /** @enum {string} */
            decision: "allow" | "deny" | "fail";
            method: string;
            host: string;
            port: number;
            detail: string;
            count: number;
        };
        session_progress: {
            turns: number;
            tool_calls: number;
            tool: string;
            spent_usd: number | null;
        };
        skill_stored: {
            skill_id: string;
        };
        system_one: {
            use: string;
            item_id: string;
            model: string;
            answer: string;
            confidence: number;
            probabilities: {
                [key: string]: number;
            };
            threshold: number;
            /** @enum {string} */
            action: "continue" | "split" | "block";
            error: string;
        };
        tool_call: {
            tool: string;
            ok: boolean;
            role?: string;
            error?: string;
        };
        turns_exhausted: {
            max_turns: number;
            tool_calls: number;
        };
        verify: {
            /** @enum {string} */
            trigger: "done" | "tool" | "cycle";
            /** @enum {string} */
            verdict: "passed" | "failed" | "unverified";
            checks: {
                name: string;
                passed: boolean;
                exit_code: number;
                gating: boolean;
                timed_out: boolean;
                duration_s: number;
            }[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The server and its dependencies. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            /** @description No valid token (`X-LHA-Token` header, or the `lha_token` cookie for reads). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description The `Host` header is not this server's loopback address (DNS rebinding). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listMissions: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The missions. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        missions: components["schemas"]["MissionSummary"][];
                    };
                };
            };
            /** @description No valid token (`X-LHA-Token` header, or the `lha_token` cookie for reads). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description The `Host` header is not this server's loopback address (DNS rebinding). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description A query parameter is invalid. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getMission: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The mission id (`lha missions`). */
                mission_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The mission. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MissionDetail"];
                };
            };
            /** @description No valid token (`X-LHA-Token` header, or the `lha_token` cookie for reads). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description The `Host` header is not this server's loopback address (DNS rebinding). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description No such mission. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listItems: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The mission id (`lha missions`). */
                mission_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The checklist items, in checklist order. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["ChecklistItem"][];
                    };
                };
            };
            /** @description No valid token (`X-LHA-Token` header, or the `lha_token` cookie for reads). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description The `Host` header is not this server's loopback address (DNS rebinding). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description No such mission (`not_found`), or its anchor cannot be read here (`anchor_unavailable`). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getItem: {
        parameters: {
            query?: {
                /** @description How many of the item's events to return: the most recent ones. */
                limit?: number;
            };
            header?: never;
            path: {
                /** @description The mission id (`lha missions`). */
                mission_id: string;
                /** @description The checklist item id. */
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The item and what was recorded about it. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        item: components["schemas"]["ChecklistItem"];
                        /** @description The ids of the items that depend on this one, in checklist order. */
                        dependents: string[];
                        cycles: string[];
                        spend: components["schemas"]["CostSummary"];
                        /** @description The most recent `limit` events about the item, oldest first. */
                        events: components["schemas"]["MissionEvent"][];
                        /** @description How many events are about the item. */
                        events_total: number;
                    };
                };
            };
            /** @description No valid token (`X-LHA-Token` header, or the `lha_token` cookie for reads). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description The `Host` header is not this server's loopback address (DNS rebinding). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description No such mission or item (`not_found`), or the mission's anchor cannot be read here (`anchor_unavailable`). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description A query parameter is invalid. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listEvents: {
        parameters: {
            query?: {
                /** @description Return events with an id greater than this (the previous page's `next_after`). */
                after?: number;
                limit?: number;
            };
            header?: never;
            path: {
                /** @description The mission id (`lha missions`). */
                mission_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of events. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        events: components["schemas"]["MissionEvent"][];
                        /** @description The cursor for the next page: the last event's id, or `after` when the page is empty. */
                        next_after: number;
                    };
                };
            };
            /** @description No valid token (`X-LHA-Token` header, or the `lha_token` cookie for reads). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description The `Host` header is not this server's loopback address (DNS rebinding). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description No such mission. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description A query parameter is invalid. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listCosts: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                /** @description The mission id (`lha missions`). */
                mission_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Totals and calls, most recent first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        summary: components["schemas"]["CostSummary"];
                        calls: components["schemas"]["CostCall"][];
                        /** @description The whole ledger summed by role: the largest known spend first, then by role. */
                        by_role: components["schemas"]["CostGroup"][];
                        /** @description The whole ledger summed by model: the largest known spend first, then by model. */
                        by_model: components["schemas"]["CostGroup"][];
                    };
                };
            };
            /** @description No valid token (`X-LHA-Token` header, or the `lha_token` cookie for reads). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description The `Host` header is not this server's loopback address (DNS rebinding). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description No such mission. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description A query parameter is invalid. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listGates: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                /** @description The mission id (`lha missions`). */
                mission_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The gates. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        gates: components["schemas"]["Gate"][];
                    };
                };
            };
            /** @description No valid token (`X-LHA-Token` header, or the `lha_token` cookie for reads). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description The `Host` header is not this server's loopback address (DNS rebinding). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description No such mission. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description A query parameter is invalid. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    streamEvents: {
        parameters: {
            query?: {
                /** @description Only this mission's messages. */
                mission_id?: string;
                /** @description Start after this event id (default: only new events). `Last-Event-ID` wins when both are sent. */
                after?: number;
            };
            header?: {
                "Last-Event-ID"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The stream (never ends on its own). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            /** @description No valid token (`X-LHA-Token` header, or the `lha_token` cookie for reads). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description The `Host` header is not this server's loopback address (DNS rebinding). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description A query parameter is invalid. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    steerMission: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The mission id (`lha missions`). */
                mission_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    note: string;
                };
            };
        };
        responses: {
            /** @description Sent to the mission's workflow; it applies the control at its next decision point. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Accepted"];
                };
            };
            /** @description No valid token (`X-LHA-Token` header, or the `lha_token` cookie for reads). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description The `Host` header is not this server's loopback address (DNS rebinding). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description No such mission. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description The mission is not durable (a local run has no control channel), or it has finished. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description The request body is invalid. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Temporal is unreachable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    snoozeMission: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The mission id (`lha missions`). */
                mission_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    seconds: number;
                };
            };
        };
        responses: {
            /** @description Sent to the mission's workflow; it applies the control at its next decision point. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Accepted"];
                };
            };
            /** @description No valid token (`X-LHA-Token` header, or the `lha_token` cookie for reads). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description The `Host` header is not this server's loopback address (DNS rebinding). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description No such mission. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description The mission is not durable (a local run has no control channel), or it has finished. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description The request body is invalid. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Temporal is unreachable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    editChecklist: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The mission id (`lha missions`). */
                mission_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    edits: components["schemas"]["ChecklistEdit"][];
                    /** @description Who edits; recorded in the anchor's event. */
                    by?: string;
                };
            };
        };
        responses: {
            /** @description Sent to the mission's workflow; it applies the control at its next decision point. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Accepted"];
                };
            };
            /** @description No valid token (`X-LHA-Token` header, or the `lha_token` cookie for reads). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description The `Host` header is not this server's loopback address (DNS rebinding). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description No such mission. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description The mission is not durable (a local run has no control channel), or it has finished. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description The request body is invalid. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Temporal is unreachable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    decideGate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The mission id (`lha missions`). */
                mission_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    decision: "approve" | "reject" | "retry" | "abort" | "impossible";
                    by: string;
                };
            };
        };
        responses: {
            /** @description Sent to the mission's workflow; it applies the control at its next decision point. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Accepted"];
                };
            };
            /** @description No valid token (`X-LHA-Token` header, or the `lha_token` cookie for reads). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description The `Host` header is not this server's loopback address (DNS rebinding). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description No such mission. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description The mission is not durable (a local run has no control channel), or it has finished. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description The request body is invalid. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Temporal is unreachable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    abortMission: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The mission id (`lha missions`). */
                mission_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": Record<string, never>;
            };
        };
        responses: {
            /** @description Sent to the mission's workflow; it applies the control at its next decision point. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Accepted"];
                };
            };
            /** @description No valid token (`X-LHA-Token` header, or the `lha_token` cookie for reads). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description The `Host` header is not this server's loopback address (DNS rebinding). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description No such mission. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description The mission is not durable (a local run has no control channel), or it has finished. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description The request body is invalid. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Temporal is unreachable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
