//go:build ignore

// gen.go writes tables.go from the JSON produced by dump_unicode.py: CPython's str predicates
// (isspace/isalnum/isdigit/isdecimal) as range tables, the final-sigma context classes, the characters whose
// NFKC form contains a URL delimiter, and the case mappings where CPython differs from Go's
// unicode.ToLower / unicode.ToUpper (full SpecialCasing mappings and Unicode-version drift).
package main

import (
	"encoding/json"
	"fmt"
	"os"
	"sort"
	"strconv"
	"unicode"
)

type dump struct {
	Space       [][2]rune         `json:"space"`
	Alnum       [][2]rune         `json:"alnum"`
	Digit       [][2]rune         `json:"digit"`
	Decimal     [][2]rune         `json:"decimal"`
	CasedNonIgn [][2]rune         `json:"cased_nonign"`
	Ignorable   [][2]rune         `json:"ignorable"`
	NFKCDanger  [][2]rune         `json:"nfkc_danger"`
	Lower       map[string]string `json:"lower"`
	Upper       map[string]string `json:"upper"`
	Casefold    map[string]string `json:"casefold"`
	Unicode     string            `json:"unicode"`
}

func main() {
	raw, err := os.ReadFile(os.Args[1])
	if err != nil {
		panic(err)
	}
	var d dump
	if err := json.Unmarshal(raw, &d); err != nil {
		panic(err)
	}
	fmt.Println("// Code generated by gen.go from CPython's unicodedata " + d.Unicode + "; DO NOT EDIT.")
	fmt.Println()
	fmt.Println("package pystr")
	fmt.Println()
	fmt.Printf("// UnicodeVersion is the unicodedata version of the CPython these tables were dumped from.\n")
	fmt.Printf("const UnicodeVersion = %q\n\n", d.Unicode)
	ranges := func(name string, rs [][2]rune) {
		fmt.Printf("var %s = []rng{\n", name)
		for _, r := range rs {
			fmt.Printf("\t{0x%04X, 0x%04X},\n", r[0], r[1])
		}
		fmt.Println("}")
		fmt.Println()
	}
	ranges("spaceTable", d.Space)
	ranges("alnumTable", d.Alnum)
	ranges("digitTable", d.Digit)
	ranges("decimalTable", d.Decimal)
	ranges("casedNonIgnorableTable", d.CasedNonIgn)
	ranges("caseIgnorableTable", d.Ignorable)
	ranges("nfkcURLDelimiterTable", d.NFKCDanger)
	exceptions := func(name string, m map[string]string, goMap func(rune) rune) {
		var keys []int
		for c := 0; c < 0x110000; c++ {
			if c >= 0xD800 && c < 0xE000 {
				continue
			}
			py, ok := m[strconv.Itoa(c)]
			if !ok {
				py = string(rune(c))
			}
			if py != string(goMap(rune(c))) {
				keys = append(keys, c)
			}
		}
		sort.Ints(keys)
		fmt.Printf("var %s = map[rune]string{\n", name)
		for _, c := range keys {
			py, ok := m[strconv.Itoa(c)]
			if !ok {
				py = string(rune(c))
			}
			fmt.Printf("\t0x%04X: %s,\n", c, strconv.QuoteToASCII(py))
		}
		fmt.Println("}")
		fmt.Println()
	}
	exceptions("lowerExceptions", d.Lower, unicode.ToLower)
	exceptions("upperExceptions", d.Upper, unicode.ToUpper)
	exceptions("casefoldExceptions", d.Casefold, unicode.ToLower)
}
